// <auto-generated />
using System;
using MadHotSpot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MadHotSpot.Migrations
{
    [DbContext(typeof(OtelAppDbContext))]
    [Migration("20210606171823_FirstDbSend")]
    partial class FirstDbSend
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MadHotSpot.Models.Ayarlar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AdSoyadZorunlu");

                    b.Property<Guid>("FirmaId");

                    b.Property<int>("FirmaKodu");

                    b.Property<double>("GunlukFiyatEURO");

                    b.Property<double>("GunlukFiyatTL");

                    b.Property<double>("GunlukFiyatUSD");

                    b.Property<string>("MikrotikDefaultSifre");

                    b.Property<string>("MikrotikIp");

                    b.Property<string>("MikrotikPass");

                    b.Property<string>("MikrotikPort");

                    b.Property<string>("MikrotikUser");

                    b.Property<bool>("Silindi");

                    b.Property<bool>("SinirsizAktif");

                    b.HasKey("Id");

                    b.ToTable("H_Ayarlar");
                });

            modelBuilder.Entity("MadHotSpot.Models.Firmalar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Aktif");

                    b.Property<DateTime>("BaslamaTarihi");

                    b.Property<DateTime>("BitisTarihi");

                    b.Property<string>("Email");

                    b.Property<string>("FirmaAdi");

                    b.Property<Guid>("FirmaId");

                    b.Property<int>("FirmaKodu");

                    b.Property<bool>("Silindi");

                    b.Property<string>("Telefon");

                    b.Property<string>("YetkiliAdSoyad");

                    b.HasKey("Id");

                    b.ToTable("H_Firmalar");
                });

            modelBuilder.Entity("MadHotSpot.Models.InternetSatis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdSoyad");

                    b.Property<bool>("Aktarildi");

                    b.Property<double>("AlinanTutar");

                    b.Property<DateTime>("BaslamaTarihi");

                    b.Property<DateTime>("BitisTarihi");

                    b.Property<string>("Doviz");

                    b.Property<Guid>("FirmaId");

                    b.Property<int>("FirmaKodu");

                    b.Property<int>("Gun");

                    b.Property<string>("Odano");

                    b.Property<string>("Sifre");

                    b.Property<bool>("Silindi");

                    b.Property<string>("Telefon");

                    b.Property<double>("Tutar");

                    b.Property<string>("VatNo");

                    b.HasKey("Id");

                    b.ToTable("H_InternetSatis");
                });

            modelBuilder.Entity("MadHotSpot.Models.Kullanicilar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<Guid>("FirmaId");

                    b.Property<int>("FirmaKodu");

                    b.Property<string>("KullaniciKodu");

                    b.Property<string>("Sifre");

                    b.Property<bool>("Silindi");

                    b.Property<string>("Telefon");

                    b.Property<string>("Yetki");

                    b.HasKey("Id");

                    b.ToTable("H_Kullanicilar");
                });
#pragma warning restore 612, 618
        }
    }
}
